package com.example.Spring_jwt_demo.entity;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;

/**
 * Represents a Customer entity in the database with fields for ID, username, password, and phone number.
 */
@Entity
public class Customer {

    /**
     * Unique identifier for the Customer. Auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long cid;

    /**
     * Username of the customer.
     */
    private String uname; // Changed to instance variable

    /**
     * Password of the customer, stored as a hashed value.
     */
    private String pwd; // Changed to instance variable

    /**
     * Phone number of the customer.
     */
    private Long phno;

    /**
     * Gets the unique ID of the customer.
     *
     * @return the customer ID.
     */
    public Long getCid() {
        return cid;
    }

    /**
     * Sets the unique ID for the customer.
     *
     * @param cid the customer ID to set.
     */
    public void setCid(Long cid) {
        this.cid = cid; // Directly set the Long value
    }

    /**
     * Gets the username of the customer.
     *
     * @return the customer's username.
     */
    public String getUname() {
        return uname; // Return instance variable
    }

    /**
     * Sets the username of the customer.
     *
     * @param uname the username to set.
     */
    public void setUname(String uname) {
        this.uname = uname; // Set instance variable
    }

    /**
     * Gets the password of the customer (stored as hashed).
     *
     * @return the customer's password.
     */
    public String getPwd() {
        return pwd; // Return instance variable
    }

    /**
     * Sets the password for the customer.
     *
     * @param pwd the password to set.
     */
    public void setPwd(String pwd) {
        this.pwd = pwd; // Set instance variable
    }

    /**
     * Gets the phone number of the customer.
     *
     * @return the customer's phone number.
     */
    public Long getPhno() {
        return phno;
    }

    /**
     * Sets the phone number for the customer.
     *
     * @param phno the phone number to set.
     */
    public void setPhno(Long phno) {
        this.phno = phno;
    }

    // Optionally, override `toString`, `equals`, and `hashCode` for better logging and comparison.
    @Override
    public String toString() {
        return "Customer{" +
                "cid=" + cid +
                ", uname='" + uname + '\'' +
                ", phno=" + phno +
                '}';
    }
}
